name: super-cool-app
base: core22 # the base snap is the execution environment for this snap
version: '1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Super Cool App
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64
    run-on: amd64

apps:
  super-cool-app:
    command: super_cool_app
    extensions:
      - flutter-stable

parts:
  super-cool-app:
    source: https://github.com/panxxhub/super-cool-app
    plugin: flutter
    flutter-target: lib/main.dart
